server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huoguo?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: chenweijia
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  #springboot上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.jsut.huoguo.pojo

